name = "Sky FABRICation 3"
author = "MSandro"
version = "0.5.7a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6fb8de344b45b670ebdf97135cd70c5295aa0ded5a16cfe86a9c13e8d5f7e01"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"
