name = "Sky FABRICation 3"
author = "MSandro"
version = "0.5.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd7cf4304f39202c85617850944d57dea7665e9780012933ea69585e7e6032b7"

[versions]
fabric = "0.14.11"
minecraft = "1.18.2"
