name = "Sky FABRICation 3"
author = "MSandro"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81695aade7edf039d7fedc393eb9818dcb7e2fb09bcdd04fbf09dcae045699ad"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
