name = "Sky FABRICation 3"
author = "MSandro"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23d13814553ff71260ecb7afb0d1f72f54ad55c9602a7989caca9f97fd376229"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
