# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				silverfish = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				piglin_brute = true
				goat = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				minecart = true
				ender_dragon = true
				evoker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				eye_of_ender = true
				wolf = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				small_fireball = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true

			[light_sources.settings.entities.minesettlements]
				civilian = true

			[light_sources.settings.entities.timeinabottle]
				accelerator = true

			[light_sources.settings.entities.botania]
				mana_burst = true
				spark = true

			[light_sources.settings.entities.mini_scaled]
				portal = true

			[light_sources.settings.entities.besmirchment]
				final_broom = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.adventurez]
				deer = true
				orc = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				wither_puppet = true
				necromancer = true
				blaze_guardian = true
				ender_whale = true
				summoner = true
				blaze_guardian_shield = true
				nightmare = true

			[light_sources.settings.entities.agape_space]
				europa_fish = true
				rocket_ship_cargo = true
				europa_fish_a = true
				rocket_ship = true
				rocket_ship_v3 = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.edenring]
				diskwing = true
				lightning_ray = true

			[light_sources.settings.entities.bewitchment]
				ghost = true
				raven = true
				vampire = true
				snake = true
				toad = true
				hellhound = true
				juniper_broom = true

			[light_sources.settings.entities.wildbackport]
				frog = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				reindeer = true
				jellyfish = true
				octopus = true
				goose = true
				songbird = true
				badgerdirt = true
				eel_freshwater = true
				squid_giant = true
				boar = true
				dragonfly = true
				whale = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				pheasant_egg = true
				shark = true
				flying_fish = true
				bobbit_worm = true
				barracuda = true
				nautilus = true
				moose = true
				tarantula = true
				badger = true
				eel_saltwater = true
				squirrel = true
				brownbear = true
				walrus = true
				horseshoecrab = true
				turkey = true
				coyote = true
				squid_colossal = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.mobscarecrow]
				villager_plushie = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.strawdummy]
				damage_number_entity = true
				strawdummy = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				void_blossom = true

			[light_sources.settings.entities.terrarianslimes]
				black_slime = true
				jungle_slime = true
				crimslime = true
				yellow_slime = true
				ice_slime = true
				king_slime = true
				baby_slime = true
				bomb = true
				mother_slime = true
				spike = true
				spiked_jungle_slime = true
				green_slime = true
				illuminant_slime = true
				red_slime = true
				pinky = true
				spiked_slime = true
				umbrella_slime = true
				blue_slime = true
				lava_slime = true
				spiked_ice_slime = true
				purple_slime = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				loading_indicator = true

			[light_sources.settings.entities.mythicmounts]
				netherbat = true
				ridinglizard = true
				firebird = true
				courierbird = true
				moth = true
				direwolf = true
				dragon = true
				archelon = true
				acencia = true
				geckotoalizard = true

			[light_sources.settings.entities.charm]
				moobloom = true
				chair = true

			[light_sources.settings.entities.the_aether]
				aerbunny = true
				poison_needle = true
				aechor_plant = true
				blue_swet = true
				moa = true

			[light_sources.settings.entities.spectrum]
				shooting_star = true

			[light_sources.settings.entities.twilightforest]
				quest_ram = true
				death_tome = true
				kobold = true
				redcap_sapper = true
				boar = true
				lich = true
				hydra = true
				hydra_mortar = true
				unstable_ice_core = true
				dwarf_rabbit = true
				winter_wolf = true
				fire_beetle = true
				carminite_golem = true
				helmet_crab = true
				lower_goblin_knight = true
				squirrel = true
				maze_slime = true
				tiny_bird = true
				lich_bolt = true
				yeti = true
				lich_bomb = true
				pinch_beetle = true
				deer = true
				harbinger_cube = true
				hedge_spider = true
				lich_minion = true
				skeleton_druid = true
				carminite_ghastguard = true
				slime_beetle = true
				carminite_ghastling = true
				armored_giant = true
				swarm_spider = true
				blockchain_goblin = true
				carminite_broodling = true
				raven = true
				adherent = true
				redcap = true
				upper_goblin_knight = true
				troll = true
				hostile_wolf = true
				mosquito_swarm = true
				tome_bolt = true
				stable_ice_core = true
				protection_box = true
				minotaur = true
				wraith = true
				alpha_yeti = true
				giant_miner = true
				snow_guardian = true
				naga = true
				penguin = true
				bighorn_sheep = true

